name: deprecations-rss
type: python

up:
  - uv

commands:
  scrape: python main.py
  server: cd docs && python -m http.server $PORT
  checks: python main.py && python rss_gen.py

open:
  app: https://deprecations-rss.myshopify.io/
