name: deprecations-rss
type: python

up:
  - uv

commands:
  generate: python run.py
  server: cd docs && python -m http.server $PORT

check:
  format: ruff check --fix --unsafe-fixes . && ruff format .
  lint: ruff check . && ruff format --check .

open:
  app: https://deprecations-rss.myshopify.io/
