# Scraper configuration for the deprecation RSS orchestrator

# Orchestrator settings
orchestrator:
  max_concurrent: 3              # Maximum number of scrapers to run concurrently
  timeout_seconds: 120           # Timeout for each scraper in seconds
  retry_failed: true            # Whether to retry failed scrapers
  fail_fast: false              # Stop on first failure

# Default scraper configuration (applies to all scrapers)
scraper_defaults:
  timeout: 60                   # HTTP request timeout in seconds
  max_retries: 3               # Maximum retry attempts for failed requests
  retry_delays: [1, 2, 4]      # Delays between retries in seconds
  cache_ttl_hours: 23          # Cache validity period in hours
  rate_limit_delay: 2.0        # Delay between requests to avoid rate limiting
  cache_dir: ".cache"          # Directory for cached responses
  user_agent: "deprecations-rss/0.1.0 (+https://github.com/leblancfg/deprecations-rss)"

# Individual scraper configurations
scrapers:
  openai:
    enabled: true
    url: "https://platform.openai.com/docs/deprecations"
    description: "OpenAI model deprecations"
    # Override defaults if needed
    timeout: 90                # OpenAI docs might be slower
    max_retries: 5             # More retries for reliability
    rate_limit_delay: 3.0      # Be conservative with rate limiting

  # Additional scrapers can be added here as they are implemented
  # anthropic:
  #   enabled: true
  #   url: "https://docs.anthropic.com/deprecations"
  #   description: "Anthropic model deprecations"
  
  # google:
  #   enabled: true
  #   url: "https://cloud.google.com/vertex-ai/docs/deprecations"
  #   description: "Google Vertex AI model deprecations"

# Data storage configuration
storage:
  type: "json"                 # Storage backend type
  data_dir: "./data"           # Directory for storing deprecation data
  backup_enabled: true         # Enable automatic backups
  backup_dir: "./data/backups" # Directory for backups
  backup_retention_days: 30    # Keep backups for this many days

# Logging configuration
logging:
  level: "INFO"                # Log level (DEBUG, INFO, WARNING, ERROR)
  file: "orchestrator.log"     # Log file path
  max_size_mb: 10             # Maximum log file size before rotation
  backup_count: 5             # Number of rotated log files to keep

# Scheduling configuration (for automated runs)
schedule:
  enabled: false              # Enable automated scheduling
  cron: "0 0 * * *"          # Run daily at midnight
  timezone: "UTC"            # Timezone for scheduling