name: Scrape Deprecations

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: |
          uv sync
          uv run playwright install chromium
      
      - name: Set up environment
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
      
      - name: Scrape and generate all feeds
        run: uv run python -m src.main
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all generated files in the new v1 structure
          git add data.json docs/v1/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update deprecation data - $(date -u +%Y-%m-%d)"
            git push
          fi