name: Scrape Deprecations

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install httpx beautifulsoup4 lxml playwright
          playwright install chromium
      
      - name: Scrape deprecations
        run: python main.py
      
      - name: Generate RSS feed
        run: python rss_gen.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add data.json docs/feed.xml docs/rss/v1/feed.xml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update deprecation data - $(date -u +%Y-%m-%d)"
            git push
          fi